### ISSUE TITLE
Selection Criteria

### ISSUE THREAD

**Issue by bhagyas** [CodeLanka/io16extended-selection#3]
The selection criteria should not include any weights. 

Not even the actual Google IO uses such weights.

**Comment by pasindud** [comment]
Is there any other reason other than "Not even the actual Google IO uses such weights." for not using weights ?.

**Comment by bhagyas** [comment]
The event has been heavily promoted as a breakaway from an 'I/O sponsorship Monopoly' from the previous primary sponsor. The earlier sponsor did not visibly discriminate any individual who wanted to attended the I/O extended event based on the usage of their own developer platform or SDK/tooling.

The current marketing around the I/O hasn't stopped from a shameless promotion of a local appstore which is filled with a large number of spammy applications as well as a Play Store clone which requires disabling Android security features to prevent users from installing apps from third party appstores.

Also not all who would attend Google I/O are Play store or mobile apps developers. (Example: Google Cloud Developers, iOS Developers who use Google APIs, Adsense/YouTube API developers, the list goes on).

Attending previous I/O or GDG events are not helpful in being used as scores attracting new individuals who want to get on board with Google Developer Platforms.

The sign up form did not mention the usage of such an algorithm. Most people would not have bothered to provide any information which would've led to being spammed with marketing messages from the primary sponsor.

There are many other reasons, but the above are among the primary concerns.

**Comment by tdevinda** [comment]
I think your point is that we used the wrong weights. Not that weighing is wrong.
First, you have to remember Dialog didn't ask us to "Accept all ideamart developers" from the list. Dialog pays for the event. Although its free for the participants. So its only fair that their devs have a boost in chance. 

We didn't put that we were selecting from an algo just because of the reason we didn't want them to put up false info. If people don't bother to fill up info, I think its fair on our side not bother and try selecting them. How hard is it to write a username?

Ideamart's content its security models are off the topic here. You can do research on their uses and uselessness separately.

**Comment by bhagyas** [comment]
Weighing is fundamentally wrong for an **open** event, regardless of who sponsors or organises it. 

Quotas would have been better to accommodate requests from sponsors rather than sacrificing the integrity of the primary event or the event organisers. 

Also a transparent process should be transparent from the beginning, including specifying the use of algorithms or criteria for selection of participants.

Agreed on the security or monetisation models or practices of the sponsor, and that needs to be rightfully raised with Google and its Developer relations team as a separate concern due to the conflict of interests.

**Comment by pasindud** [comment]
Thank You for your comments we will look into this next time.

**Comment by THPubs** [comment]
Unfortunately Bhagya is correct. The algorythm is not right and unfair from the start.

First, you give more points to previous participants. Why? Don't you want to help the new? There are many fresh minds which need to attend to this event. We need to help them. The whole community help them but tried to keep them out and put only the people who already are experts? That's not right.

Next you are giving 20 points to people who have ideamart apps. That's totally unfair and extremely unethical. Yes I understand that Dialog is sponsoring the event but there are other ways to pay back using ads and stuff. But this is totally sick.

As Bhagya mentioned, there topics are not only android related. But you give more points to people who have playstore apps. Why? What about people who wish to learn to Android development and haven't yet created an app? Again putting the new people to the bottom.

I'm totally upset about the algorythm and already lost my faith towards the GDG. I'm not trying to argue. There are many people who think you did the wrong thing. Please think before arguing and fix it next time. Thank you.
